### ISSUE TITLE
This mod does not work properly in the game

### ISSUE THREAD

**Issue by DAYYYYa** [kennyhngo/LethalCompany-NightVision#1]
I tried to modify the cfg file, but the button to turn on the night vision device did not work, nor did it after the modification

**Comment by DAYYYYa** [comment]
But this mod does disable the night vision device, which is turned on by default

**Comment by kennyhngo** [comment]
What button did you rebind it to? Also, if you click on it outside, it will toggle it on (e.g. if using default C key, then typing CONFIRM will toggle it on).

**Comment by DAYYYYa** [comment]
I don't understand what you mean by typing C and confirming, don't you press the button

**Comment by DAYYYYa** [comment]
Do you need to do anything other than press a specific button?

**Comment by kennyhngo** [comment]
If you could send me a video of you using it on discord, I'll be happy to help you out. My username is kentrosity

**Comment by kennyhngo** [comment]
I've published a new version so see if it works for you now. Hopefully it does!
