### ISSUE TITLE
I hope NightVision can be opened by default

### ISSUE THREAD

**Issue by smilepeak** [kennyhngo/LethalCompany-NightVision#2]
The NightVision function is enabled by default when entering the game, without the need to press C
Thank you🌹🌹🌹

**Comment by kennyhngo** [comment]
Would you like the option to configure the options so it is on by default?

**Comment by smilepeak** [comment]
Of course, that's the best. Thank you

**Comment by smilepeak** [comment]
I have used a new version, but it seems that this feature is not working and the configuration file is set to true

**Comment by kennyhngo** [comment]
Whoops, I forgot to repatch it with the correct build, I'll fix that later today and also publish it to the thunderstore

**Comment by smilepeak** [comment]
Okay, thank you🌹

**Comment by smilepeak** [comment]
Sorry~~but I would like to remind you that the version 1.1.3 I am using does not automatically enable NightVision, the Default behavior has been set to true, and Thunderstore has not released a new version~It is still 1.1.2🌹🌹🌹
![1](https://github.com/kennyhngo/LethalCompany-NightVision/assets/73094803/4281c843-95c9-4e10-a454-1dac27c46abf)

**Comment by kennyhngo** [comment]
I've just pushed a new version! I have had a few friends tested it and it should work. Be on the lookout for it on thunderstore. I will be closing this issue this Saturday if no further bugs arise.

**Comment by smilepeak** [comment]
Okay, everything is normal now
