### ISSUE TITLE
Change color night vision to black

### ISSUE THREAD

**Issue by EsanXD** [kennyhngo/LethalCompany-NightVision#5]
Hi can u make the night vision color to black so that you cant see very well

**Comment by kennyhngo** [comment]
Hi! Just disable fog toggle and reduce the intensity. Hope this helps.

**Comment by EsanXD** [comment]
no can you make flashlight light black please? I see too much with the flashlight

**Comment by kennyhngo** [comment]
sorry, i only work with environmental lighting

**Comment by EsanXD** [comment]
can you make the lighting max_int. the outlines on objects kind of hurts my eyes. i'd like an option to see only white. thank you!

**Comment by kennyhngo** [comment]
all configurable in settings. i also have no control over the coloring

**Comment by EsanXD** [comment]
can u make the mod configurable in game?

**Comment by EsanXD** [comment]
i dont want to go into the settings to configure the mod

**Comment by kennyhngo** [comment]
sure, i'll find a way to do that

**Comment by EsanXD** [comment]
thanks man youre the best!

**Comment by EsanXD** [comment]
actually my dog just ate my computer. thanks for the help. you're the best!
