### ISSUE TITLE
sure, i'll find a way to do that

### ISSUE THREAD

**Issue by EsanXD** [kennyhngo/LethalCompany-NightVision#6]
sure, i'll find a way to do that
Why isnt it done yet
_Originally posted by @kennyhngo in https://github.com/kennyhngo/LethalCompany-NightVision/issues/5#issuecomment-1935223004_

**Comment by kennyhngo** [comment]
Marked as duplicate, see #5

**Comment by EsanXD** [comment]
ah thanks i didnt see #5
