### ISSUE TITLE
Night vision flickering in combination with other mods

### ISSUE THREAD

**Issue by bennipauly** [kennyhngo/LethalCompany-NightVision#9]
Hi,
I recently had the issue, that the night vision was flickering in the dungeon. When I'm moving my mouse or move in general, the night vision sometimes flickers. I have other mods installed and also tried to disable each mod one by one to maybe get the mod that causes this problem, but I did not find anything...

**Comment by bennipauly** [comment]
ok seems it happened because of an EmotesAPI

**Comment by kennyhngo** [comment]
Glad you were able to resolve that!
